### ISSUE TITLE
.size()  in jquery 3  deprecated

### ISSUE THREAD

**Issue by agapetus** [lisps/ajaxedit#4]
Hello

It seems that Dokuwiki "Hogfather" is using jQuery 3 where ".size()" ist deprecated.

https://api.jquery.com/size/
> Note: This method has been removed in jQuery 3.0. Use the .length property instead.

After changing ".size()" to ".length" in script.js  everything works fine.

**Comment by menewol** [comment]
i second this!

**Comment by menewol** [comment]
i set up a pull-request to fix the two calls in script.js on line 133, respectivly line 144, to use .length instead of .size().

You might want to take a look at it, and merge it if you think its fine. we are already using these changes in production, seemingly without any impact. 

Best regards,

menewol

**Comment by peterfromearth** [comment]
fixed with #5
